---
title: First Things First
author: Hope Snyder
date: '2020-04-30'
slug: first-things-first
categories:
  - About
tags:
  - intro
  - about
description: 'Welcome to my new blog.  This is just an introduction for you and for me.'
publishDate: '2020-04-30T15:23:40-05:00'
images: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## Quote as Introduction:
<div align="center">**"The first time you do a thing is always exciting."**</div>

I believe this quote is attributed to Agatha Cristie, the wonderful mystery novelist, but I feel that so many people have expressed the exact same sentiment.  

Feelings about what i was feeling about the blog

## Who am I?

I'm Hope and I am a burgeoning data scientist.  I have begun work on my doctoral disseration in Quantitative Psychology at the University of Missouri looking at context effects when making choices. My undergraduate degree is in Mathematics and Psychology and I want to use all of the skills I got from both of these areas.  I truly believe that data science is the perfect career to marry these two areas together.

My career interests involve learning and sharing the world of data science.   I have experience with machine learning and feature engineering, Bayesian statistics, and GIT version control.  My analysis tool of choice is R, but I am working on learning Python as well.  I am committed to continue learning about each of these topics as well as cloud computing and database software.  I have also cofounded an RLadies chapter in Mid-Missouri, [CodeR-Ladies](https://code-rladies.github.io/).

Outside of the professional world, I am an avid writer, a student of Bob Ross and Hogwarts (seriously! register [here](http://www.hogwartsishere.com/courses/)!), and I go rock climbing whenever I can.

## About the blog

what is it going to be about and why im writing it.

Should I even try to include a picture?

